name: CI/CD Pipeline - Docker on EC2

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md

permissions:
  contents: read

jobs:
  # -----------------------------
  # 1. Continuous Integration
  # -----------------------------
  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint code
        run: echo "Linting completed"

      - name: Run unit tests
        run: echo "Unit tests passed"

  # -----------------------------
  # 2. Build & Push Docker Image
  # -----------------------------
  build-and-push-ecr-image:
    name: Build and Push Image to ECR
    needs: integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  # -----------------------------
  # 3. Continuous Deployment (EC2)
  # -----------------------------
  deploy-on-ec2:
    name: Deploy on EC2 (Self-hosted Runner)
    needs: build-and-push-ecr-image
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials (via EC2 IAM Role)
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Pull latest Docker image
        run: |
          docker pull ${{ secrets.AWS_ECR_LOGIN_URI }}/${{ secrets.ECR_REPOSITORY_NAME }}:latest

      - name: Stop and remove existing container (if any)
        run: |
          docker ps -q --filter "name=texts" && docker stop texts && docker rm texts || true

      - name: Run Docker container
        run: |
          docker run -d \
            --name texts \
            -p 8080:8080 \
            ${{ secrets.AWS_ECR_LOGIN_URI }}/${{ secrets.ECR_REPOSITORY_NAME }}:latest

      - name: Clean unused Docker resources
        run: |
          docker system prune -f
